name: Monorepo CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: 2. Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: 3. Setup Node.js and Cache Dependencies
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "pnpm"

      - name: 4. Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: 5. Run Linter
        run: pnpm turbo lint

      - name: 6. Run Type Checking
        run: pnpm turbo check-types

      - name: 7. Run Build
        run: pnpm turbo build
